project:
  type: website
  render:
    - "*.qmd"
    - "*.Rmd"
    - "*.md"
    - "!files/"

website:
  title: "Capstone in Cyber: Security & Policy"
  favicon: "files/img/sobolev-cyber-logo.png"
  navbar:
    pinned: true
    background: "#d47f41"
    right:
       - text: "Upper Folder"
         href: ..
       - text: "Index"
         href: index
       - text: "CyberSpace"
         href: https://utd-cyber.github.io/
#      - syllabus.qmd
#      - schedule.qmd
#      - syllabus.qmd
#      - schedule.qmd
#      - text: "Materials"
#        file: materials/index.qmd
#      - text: "Assignments"
#        file: assignments/index.qmd
#      - text: "Ed"
#        href: https://edstem.org/us/courses/45093/discussion/
#      - text: "Gradescope"
#        href: https://www.gradescope.com/courses/589033

  sidebar:
    - title: "Materials"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Overview"
          contents:
            - materials/index.qmd
        # - section: "Course Materials"
        #  contents:
            # - text: "Week 13: Panel and Clustered Data"
            #   file: materials/week_13.qmd
              
    - title: "Assignments"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Resources"
          contents:
            - assignments/index.qmd
            - assignments/problem-sets.qmd
        - section: "Assignments"
          contents:
            - text: "Problem Set 1"
              file: assignments/01_problem_set.qmd
            - text: "Problem Set 2"
              file: assignments/02_problem_set.qmd
            - text: "Problem Set 3"
              file: assignments/03_problem_set.qmd
            - text: "Problem Set 4"
              file: assignments/04_problem_set.qmd
            - text: "Problem Set 5"
              file: assignments/05_problem_set.qmd
            - text: "Problem Set 6"
              file: assignments/06_problem_set.qmd
            - text: "Problem Set 7"
              file: assignments/07_problem_set.qmd
            - text: "Problem Set 8"
              file: assignments/08_problem_set.qmd
            - text: "Problem Set 9"
              file: assignments/09_problem_set.qmd
            - text: "Problem Set 10"
              file: assignments/10_problem_set.qmd

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true

execute:
  freeze: auto



