---
title: "Capstone in Cyber"
subtitle: "Spring '24"
details: UT Dallas
sidebar: false
toc: false
page-layout: full
column: page
format:
  html:
    # include-after-body: 
    # - styles.css
    # - custom-script.js
    template-partials:
      - html/home/title-block.html
course-logo: /files/img/sobolev-cyber-logo.png
---

- 1 2 3
  * 3 4 5

::: {.custom-details}

**::: {.custom-summary}**Click to see details**:::**

::: {.hidden-content}
This content is hidden by default and will be shown when the summary is clicked.
:::

:::



::: {.callout}

# Guidelines 3
This is an example of a callout with a title  3.

# Guidelines 4
This is an example of a callout with a title  4.


:::

text 1

::: {.callout-warning collapse="true"}
## Topic 2
This is an example of a callout with a title  3.
  ::: {.callout-warning collapse="true"}
  ## Topic 3
  This is an example of a callout with a title  3.
  :::

:::


::: {.grid}

  ::: {.g-col-6}
  <iframe src="slides.pdf" width="100%"></iframe>
  :::

  ::: {.g-col-6}
  **Slides**

  □ [Machine Learning](slides.pdf)

  **Code** 

  □ [R Handout 3: Machine Learning](R-Handout-3-ML-I.Rmd.zip)

  □ [Dog Look as Data Table](dogs.txt)

  :::

:::



# Materials

|  | | 
|----------|----------|
|**Slides**                        | **Code** | 
| □ [Machine Learning](slides.pdf) | □ [R Handout 3: Machine Learning](R-Handout-3-ML-I.Rmd.zip) | 
|                                  | □ [Dog Look as Data Table](dogs.txt)| 
||<iframe src="slides.pdf" height="100%"| 

sadfasdfasd



# Servers

<iframe src="slides.pdf" height="100%"></iframe>


## Sub-Servers


::: {.panel-tabset}
# 1 Code Execution
```{r}
url <- 'cyber-utd.github.io'
url
```

# 2 Server
<script type="text/javascript" src="//cdn.datacamp.com/dcl-react.js.gz"></script>


<div data-datacamp-exercise data-lang="r" data-show-run-button="true" data-no-lazy-loading="true">
	<code data-type="pre-exercise-code">
		# This will get executed each time the exercise gets initialized
		b = 6
	</code>
	<code data-type="sample-code">
		# Create a variable a, equal to 5


		# Print out a


	</code>
	<code data-type="solution">
		# Create a variable a, equal to 5
		a <- 5

		# Print out a
		print(a)
	</code>
	<code data-type="sct">
		test_object("a")
		test_function("print")
		success_msg("Great job!")
	</code>
	<div data-type="hint">Use the assignment operator  to create the variable <code>a</code>.</div>
</div>


# 3 Other Experiments









:::

text

::: {.collapse}
### Collapsible Section Title
Content that can be shown or hidden.
:::






Code Starts Here





<!--

-->

