project:
  type: website

website:
  title: "Open-Source Intelligence [S'24]"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

exclude: ['*.Rmd']

